version: '3.8'

services:
  student-dss:
    build: .
    container_name: student-dss
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
